#!/usr/bin/env bash
STEP=${1:-5}
LOCK="/tmp/volume.lock"

(
  flock -n 9 || exit 0
  CUR=$(pactl get-sink-volume @DEFAULT_SINK@ | awk -F'/' 'NR==1{gsub(/%/,"",$2); print int($2)}')
  NEW=$((CUR - STEP))
  (( NEW < 0 )) && NEW=0
  pactl set-sink-volume @DEFAULT_SINK@ ${NEW}%
) 9>"$LOCK"


